[build]
publish = "public"
command = "hugo version; hugo mod get; hugo --minify; cp _redirects public/"

[build.environment]
HUGO_VERSION = "0.106.0"

[context.deploy-preview]
command = "hugo version; hugo mod get; hugo --minify -b $DEPLOY_PRIME_URL; cp _redirects public/"
