name: "Update financial dashboard"

on:
  push:
    paths:
      - automation/finanse/finanse.csv
      - .github/workflows/finance.yaml
  schedule:
    - cron: "0 4 * * 0"

jobs:
  dashboard:
    runs-on: ubuntu-latest
    name: Update financial dashboard
    steps:
      - uses: actions/checkout@v2.5.0
      - uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.10'
      - name: Update dashboard
        run: |
          cd automation/finanse
          pip install -r requirements.txt
          python dashboard.py
          git add ../../layouts/shortcodes/finanse.html
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4.15.3
        with:
          commit_message: Automated financial dashboard snapshot
