name: "Update financial dashboard"

on:
  push:
    paths: automation/finanse/finanse.csv
  schedule:
    - cron: "0 4 * * 0"

jobs:
  dashboard:
    runs-on: ubuntu-latest
    name: Update financial dashboard
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Update dashboard
        run: |
          cd automation/finanse
          pip install -r requirements.txt
          python dashboard.py
          git add index.html
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated financial dashboard snapshot
